version: "3"
services:
  db2:
    build: ./dbserver
    container_name: play_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: MySql1
      MYSQL_PASSWORD: MySql1
      TZ: 'Asia/Tokyo'
    command: mysqld
    volumes:
      - ./dbserver/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./dbserver/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
